[features]
seeds = false
skip-lint = false

[programs.localnet]
matrix_system = "DegWuGAfwzMFK5BWC33q6XW7Ebk7fesZShuaXh2HveHS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
